{"uuid": "1b9623b0-f8f4-4bc4-940b-6b01ab1bba17", "children": ["ab5020e8-99c5-4b57-882b-7865d105840f", "1f5e0f2b-89c1-4818-90f5-f5146928e70a", "0c9b6e14-2ce8-4579-9823-213cd7bd6d80"], "befores": [{"name": "init_driver", "status": "broken", "statusDetails": {"message": "AttributeError: cls not available in session-scoped context\n", "trace": "  File \"C:\\Users\\Agiliad\\Desktop\\Python\\pythonProject1\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Agiliad\\Desktop\\Python\\pythonProject1\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Agiliad\\Desktop\\Python\\pythonProject1\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\Agiliad\\Desktop\\Python\\pythonProject1\\Tests\\conftest.py\", line 18, in init_driver\n    request.cls.driver= web_driver\n  File \"C:\\Users\\Agiliad\\Desktop\\Python\\pythonProject1\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 476, in cls\n    raise AttributeError(f\"cls not available in {self.scope}-scoped context\")\n"}, "start": 1686898137886, "stop": 1686898140123}], "start": 1686898137886, "stop": 1686898141136}