{"uuid": "fd11531c-127c-49cd-ba69-0ab595fb4c23", "children": ["240295d3-32c1-40a6-8570-96da47f6081a", "e9961240-97b2-4265-b698-4ea48e831def", "3f07dbc6-d51c-4eec-a793-c25314100cbe"], "befores": [{"name": "init_driver", "status": "broken", "statusDetails": {"message": "AttributeError: cls not available in session-scoped context\n", "trace": "  File \"C:\\Users\\Agiliad\\Desktop\\Python\\pythonProject1\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Agiliad\\Desktop\\Python\\pythonProject1\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Agiliad\\Desktop\\Python\\pythonProject1\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\Agiliad\\Desktop\\Python\\pythonProject1\\Tests\\conftest.py\", line 22, in init_driver\n    request.cls.driver= web_driver\n  File \"C:\\Users\\Agiliad\\Desktop\\Python\\pythonProject1\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 476, in cls\n    raise AttributeError(f\"cls not available in {self.scope}-scoped context\")\n"}, "start": 1686898017677, "stop": 1686898020068}], "start": 1686898017677, "stop": 1686898021216}