{"uuid": "773ae4d4-802e-4786-935e-163a529aa0c8", "children": ["e89c6032-f790-488a-a140-c66f2d66a4ba", "4e6cdbb1-5031-4237-881b-d6b7691a3eba", "a47bc2bb-5ade-4aba-84a1-ef60f478d3a2"], "befores": [{"name": "init_driver", "status": "broken", "statusDetails": {"message": "AttributeError: cls not available in session-scoped context\n", "trace": "  File \"C:\\Users\\Agiliad\\Desktop\\Python\\pythonProject1\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Agiliad\\Desktop\\Python\\pythonProject1\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Agiliad\\Desktop\\Python\\pythonProject1\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\Agiliad\\Desktop\\Python\\pythonProject1\\Tests\\conftest.py\", line 18, in init_driver\n    request.cls.driver= web_driver\n  File \"C:\\Users\\Agiliad\\Desktop\\Python\\pythonProject1\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 476, in cls\n    raise AttributeError(f\"cls not available in {self.scope}-scoped context\")\n"}, "start": 1686897461818, "stop": 1686897464028}], "start": 1686897461818, "stop": 1686897465065}