{"uuid": "8d4a8f84-fe1f-499e-82ac-79559b416e2b", "children": ["04750860-33a1-492b-905d-58f5ba8a9431", "1d78a7ad-5e0d-4a40-a298-3d6331e35ea6", "5c2374b5-6615-4c4f-8a8d-80fe4c55ce11"], "befores": [{"name": "init_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_NAME_NOT_RESOLVED\n  (Session info: chrome=114.0.5735.110)\nStacktrace:\nBacktrace:\n\tGetHandleVerifier [0x0046A813+48355]\n\t(No symbol) [0x003FC4B1]\n\t(No symbol) [0x00305358]\n\t(No symbol) [0x00301B33]\n\t(No symbol) [0x002F8CA5]\n\t(No symbol) [0x002F9D0A]\n\t(No symbol) [0x002F9003]\n\t(No symbol) [0x002F8355]\n\t(No symbol) [0x002F82EC]\n\t(No symbol) [0x002F6F26]\n\t(No symbol) [0x002F7688]\n\t(No symbol) [0x00306B52]\n\t(No symbol) [0x0035CF01]\n\t(No symbol) [0x0034A73C]\n\t(No symbol) [0x0035C922]\n\t(No symbol) [0x0034A536]\n\t(No symbol) [0x003282DC]\n\t(No symbol) [0x003293DD]\n\tGetHandleVerifier [0x006CAABD+2539405]\n\tGetHandleVerifier [0x0070A78F+2800735]\n\tGetHandleVerifier [0x0070456C+2775612]\n\tGetHandleVerifier [0x004F51E0+616112]\n\t(No symbol) [0x00405F8C]\n\t(No symbol) [0x00402328]\n\t(No symbol) [0x0040240B]\n\t(No symbol) [0x003F4FF7]\n\tBaseThreadInitThunk [0x76CA00C9+25]\n\tRtlGetAppContainerNamedObjectPath [0x774F7B4E+286]\n\tRtlGetAppContainerNamedObjectPath [0x774F7B1E+238]\n\n", "trace": "  File \"C:\\Users\\Agiliad\\Desktop\\Python\\pythonProject1\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Agiliad\\Desktop\\Python\\pythonProject1\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Agiliad\\Desktop\\Python\\pythonProject1\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\Agiliad\\Desktop\\Python\\pythonProject1\\Tests\\conftest.py\", line 17, in init_driver\n    web_driver.get(TestData.Base_Url)\n  File \"C:\\Users\\Agiliad\\Desktop\\Python\\pythonProject1\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 449, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"C:\\Users\\Agiliad\\Desktop\\Python\\pythonProject1\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Agiliad\\Desktop\\Python\\pythonProject1\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1686899919421, "stop": 1686899937555}], "start": 1686899919421, "stop": 1686899939557}