{"uuid": "ec483078-052c-41d8-8007-0b551d9808fc", "children": ["9a8e3fd4-9a88-474a-899f-a8021f546c9f", "c463e8e9-d547-483e-9b5c-10514807dee6", "57f157c1-810c-4ffd-999f-4d5148b7b3f3"], "befores": [{"name": "init_driver", "status": "broken", "statusDetails": {"message": "AttributeError: cls not available in session-scoped context\n", "trace": "  File \"C:\\Users\\Agiliad\\Desktop\\Python\\pythonProject1\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Agiliad\\Desktop\\Python\\pythonProject1\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Agiliad\\Desktop\\Python\\pythonProject1\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\Agiliad\\Desktop\\Python\\pythonProject1\\Tests\\conftest.py\", line 18, in init_driver\n    request.cls.driver= web_driver\n  File \"C:\\Users\\Agiliad\\Desktop\\Python\\pythonProject1\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 476, in cls\n    raise AttributeError(f\"cls not available in {self.scope}-scoped context\")\n"}, "start": 1686894802262, "stop": 1686894804496}], "start": 1686894802262, "stop": 1686894805487}