{"uuid": "aecd33ff-3cb5-48b9-a268-924bfaf69bc8", "children": ["ff81d2ac-6bc0-4708-a778-d5b99efe7eaa", "b992667a-78ed-4436-9aac-7a02b7359502", "e0e3d757-8895-4dd3-a5ac-fdf0d8da587b"], "befores": [{"name": "init_driver", "status": "broken", "statusDetails": {"message": "AttributeError: cls not available in session-scoped context\n", "trace": "  File \"C:\\Users\\Agiliad\\Desktop\\Python\\pythonProject1\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Agiliad\\Desktop\\Python\\pythonProject1\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Agiliad\\Desktop\\Python\\pythonProject1\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\Agiliad\\Desktop\\Python\\pythonProject1\\Tests\\conftest.py\", line 26, in init_driver\n    request.cls.driver= web_driver\n  File \"C:\\Users\\Agiliad\\Desktop\\Python\\pythonProject1\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 476, in cls\n    raise AttributeError(f\"cls not available in {self.scope}-scoped context\")\n"}, "start": 1686894942687, "stop": 1686894944827}], "start": 1686894942687, "stop": 1686894945862}